build:
  keep_extension_source: true
  disable_asset_copy: false
  browserslist: '> 0.1% and not dead'
  cleanup_paths:
    - imports
    - var/cache
    - var/log
deployment:
  extension-management:
    enabled: true

    exclude:
      - 'FroshDeploymentHelper'
      - 'FroshLazySizes'

  hooks:
    pre-update: |
      ../../current/bin/dump.sh
  store:
    license-domain: '##DOMAIN##'


validation:
  ignore:
    - identifier: 'phpstan/shopware.forbidLocalDiskWrite'
    - identifier: 'phpstan/shopware.internalMethodCall'