name: Cleanup Flex testing endpoint
on:
  pull_request_target:
    types: [closed]
defaults:
  run:
    shell: bash
jobs:
  call-flex-cleanup:
    runs-on: [self-hosted, linux, Ubuntu-20.04]
    uses: symfony/recipes/.github/workflows/callable-flex-cleanup.yml@main