name: Update Flex endpoint
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  call-flex-update:
    runs-on: [self-hosted, linux, Ubuntu-20.04]
    concurrency: flex-update-${{ github.ref }}
    steps:
      - uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main